DROP TABLE IF EXISTS PC_CONFIG;
CREATE TABLE PC_CONFIG(
	CONFIG_NAME varchar(100),
	CONFIG_VALUE varchar(100)
);

DROP TABLE IF EXISTS ESRS_CONFIG;
CREATE TABLE ESRS_CONFIG(
	CONFIG_NAME varchar(100),
	CONFIG_VALUE varchar(100)
);

DROP TABLE IF EXISTS DEVICE_KEY;
CREATE TABLE DEVICE_KEY(
MODEL varchar(300) NOT NULL, 
SERIAL_NUMBER varchar(300) NOT NULL,
DEVICE_KEY varchar(300),
CREATED_DATE varchar(300),
UPDATED_DATE varchar(300),
CONNECTIVITY_ENABLED varchar(300),
LAST_CONNECTIVITY_UPDATED_DATE varchar(300), 
REGION varchar(300), 
DISABLE_BY varchar(300), 
DISABLE_ON varchar(300) 
);

DROP TABLE IF EXISTS EMC_GATEWAY_SERIALNUMBER;
CREATE TABLE EMC_GATEWAY_SERIALNUMBER(
	EMC_SERIAL_NUMBER varchar(100) NOT NULL,
	CSI_SERIAL_NUMBER varchar(100) NOT NULL,
	PARTY_NUMBER varchar(100),
	INSTALL_DUNS varchar(100)
);

DROP TABLE IF EXISTS PARTY;
CREATE SCHEMA ESRS;
CREATE TABLE ESRS.PARTY(
	PARTY_NUMBER varchar(100) NOT NULL,
	PARTY_NAME varchar(100),
	ADDRESS varchar(100),
	CITY varchar(100),
	STATE varchar(100),
	ZIP varchar(100),
	COUNTRY varchar(100),
	REGION varchar(100),
	DISTRICT varchar(100),
	DIVISION varchar(100),
	THEATER varchar(100),
	PROVINCE varchar(100),
	LAST_UPD_DATE varchar(100) NOT NULL,
	CREATE_DATE varchar(100) NOT NULL
);

DROP TABLE IF EXISTS ELMS_MODEL_MAPPING;
CREATE TABLE ESRS.ELMS_MODEL_MAPPING(
	MODEL_NAME varchar(100),
	ELMS_MODEL_NAME varchar(100)
);


DROP TABLE IF EXISTS PC_INSTALL_REQUEST;
CREATE TABLE esrs.PC_INSTALL_REQUEST(
	INSTALL_REQUEST_ID smallint NOT NULL,
	CUSTOMER_ID varchar(100) NOT NULL,
	SERIAL_NUMBER varchar(100) NOT NULL,
	REQUEST_TYPE varchar(100) NOT NULL,
	REQUEST_DATE varchar(100),
	CERT_ISSUED varchar(100),
	VERSION varchar(100),
	ACCESS_KEY_ID smallint
);

DROP TABLE IF EXISTS ITEM_INSTANCE;
CREATE TABLE ESRS.ITEM_INSTANCE(
ITEM_INSTANCE_ID varchar(100) NOT NULL,
PARTY_NUMBER varchar(100) NOT NULL,
SERIAL_NUMBER varchar(100) NOT NULL,
PART_NUMBER varchar(100),
PRODUCT_TYPE varchar(100),
MODEL varchar(100),
PART_DESCRIPTION varchar(100),
PART_TYPE varchar(100),
INSTALL_DUNS varchar(100),
SERVICE_DUNS varchar(100),
ITEM_STATUS varchar(100),
LAST_UPD_DATE varchar(100),
CREATE_DATE varchar(100),
LINE varchar(100),
CUSTOMER_PRODUCT_ID varchar(100)
);

DROP TABLE IF EXISTS ITEM_INSTANCE_WITH_DUPES;
CREATE TABLE ESRS.ITEM_INSTANCE_WITH_DUPES(
ITEM_INSTANCE_ID varchar(100) NOT NULL,
PARTY_NUMBER varchar(100) NOT NULL,
SERIAL_NUMBER varchar(100) NOT NULL,
PART_NUMBER varchar(100),
PRODUCT_TYPE varchar(100),
MODEL varchar(100),
PART_DESCRIPTION varchar(100),
PART_TYPE varchar(100),
INSTALL_DUNS varchar(100),
SERVICE_DUNS varchar(100),
ITEM_STATUS varchar(100),
LAST_UPD_DATE varchar(100),
CREATE_DATE varchar(100),
LINE varchar(100),
CUSTOMER_PRODUCT_ID varchar(100)
);

DROP TABLE IF EXISTS ESRS.PRODUCT_TYPE;
CREATE TABLE ESRS.PRODUCT_TYPE(ESRS_PRODUCT_TYPE varchar(100),DRM_PRODUCT_TYPE varchar(100),COMMENTS varchar(100));
CREATE SEQUENCE esrs.SEQ_PC_INSTALL_REQUEST START WITH 38756 INCREMENT BY 1;

DROP TABLE IF EXISTS CONNECTIVITY_ACC_KEY_DETAILS;
CREATE SCHEMA SRS4;
CREATE TABLE SRS4.CONNECTIVITY_ACC_KEY_DETAILS(
    KEY_ID        smallint        IDENTITY PRIMARY KEY, 
    TRANSACTION_ID        varchar(100),
    USER_ID  varchar(100),
    DCN varchar(100),
    UCID varchar(100),
    SERIALNUMBER_SERVICETAG varchar(100),
    ACCESS_KEY varchar(100),
    PIN varchar(100),
    CREATE_TIME varchar(100),
    EXPIRE_TIME varchar(100),
    USED_TIME varchar(100),
    STATUS varchar(100),
    MODEL_NAME varchar(100),
    PRODUCT_TYPE varchar(100),
    TYPE varchar(100)   
);

DROP TABLE IF EXISTS CONNECTIVITY_ACCESS_KEY_USER;
CREATE TABLE SRS4.CONNECTIVITY_ACCESS_KEY_USER(
    USER_ID        varchar(100)        NOT NULL, 
    NT_ID        varchar(100),
    FIRST_NAME  varchar(100),
    LAST_NAME varchar(100),
    EMAIL varchar(100),
    PHONE varchar(100)   
);

DROP TABLE IF EXISTS SAE_REGISTRATION_DETAILS;
CREATE TABLE SRS4.SAE_REGISTRATION_DETAILS(
SERIAL_NUMBER varchar(100) NOT NULL,
DEVICE_KEY varchar(300),
VERSION varchar(100) NOT NULL,
REGISTRATION_ID varchar(100),
REGISTRATION_STATUS varchar(100), 
IP_ADDRESS varchar(100) NOT NULL, 
CREATED_DATE varchar(100) NOT NULL, 
MODIFIED_DATE varchar(100) NOT NULL,
GATEWAYMODEL varchar(128) NOT NULL
);

DROP TABLE IF EXISTS SRS_USERS;
CREATE TABLE SRS4.SRS_USERS(
USER_ID varchar(100) NOT NULL,
EMAIL varchar(300),
NAME varchar(300) NOT NULL,
GDUNS varchar(100),
DOMAIN varchar(100), 
NT_ID varchar(100),
LOGIN varchar(100),
PHONE varchar(100),
SOURCE varchar(100),
STATUS varchar(100),
LAST_UPD_DATE varchar(100) NOT NULL,
CREATE_DATE varchar(100) NOT NULL,
IMPORT_STATUS varchar(100)
);

DROP TABLE IF EXISTS USER_GROUPS;
CREATE TABLE SRS4.USER_GROUPS(
USER_ID varchar(100) NOT NULL,
GROUP_ID varchar(100) NOT NULL,
LAST_UPD_DATE varchar(100) NOT NULL,
CREATE_DATE varchar(100) NOT NULL
);

DROP TABLE IF EXISTS GATEWAY_MODELS;
CREATE TABLE SRS4.GATEWAY_MODELS(
MODEL varchar(128),
ELMS_MODEL_NAME varchar(64),
CLIENT_VALIDATION varchar(1)
);